foreground         #c6c2c2
background         #1b0c0c
background_opacity 1.0
cursor             #c6c2c2

active_tab_foreground     #1b0c0c
active_tab_background     #c6c2c2
inactive_tab_foreground   #c6c2c2
inactive_tab_background   #1b0c0c

active_border_color   #c6c2c2
inactive_border_color #1b0c0c
bell_border_color     #575757

color0       #1b0c0c
color8       #6f5b5b
color1       #575757
color9       #747474
color2       #6c6c6c
color10      #919191
color3       #7e7e7e
color11      #A8A8A8
color4       #8a8a8a
color12      #B8B8B8
color5       #9c9c9c
color13      #D0D0D0
color6       #ababab
color14      #E5E5E5
color7       #998f8f
color15      #c6c2c2
